# serviceaccount.yaml
# Ryan Loiselle â€” Developer / Architect | GitHub Copilot | February 2026

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "<APP_NAME>.serviceAccountName" . }}
  labels:
    {{- include "<APP_NAME>.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
